FROM ubuntu:22.04

RUN apt-get update

RUN apt-get install -y gcc g++
RUN apt-get install -y git
RUN apt-get install -y cmake
RUN apt-get install -y pkg-config
RUN apt-get install -y libopenmpi-dev
RUN apt-get install -y openmpi-bin
RUN apt-get install -y libsuitesparse-dev
RUN apt-get install -y gmsh
RUN apt-get install -y libboost-all-dev
RUN apt-get install -y libmpfr-dev
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-venv
RUN apt-get install -y vim

WORKDIR /dune

RUN git clone https://gitlab.dune-project.org/core/dune-common.git
RUN git clone https://gitlab.dune-project.org/core/dune-geometry.git
RUN git clone https://gitlab.dune-project.org/core/dune-grid.git
RUN git clone https://gitlab.dune-project.org/core/dune-localfunctions.git
RUN git clone https://gitlab.dune-project.org/core/dune-istl.git
RUN git clone https://gitlab.dune-project.org/extensions/dune-alugrid.git
RUN git clone https://gitlab.dune-project.org/maximilian.hoerl/dune-fem.git
RUN git clone https://gitlab.dune-project.org/samuel.burbulla/dune-mmesh.git
RUN git clone https://github.com/maximilianhoerl/mmdgpy.git

RUN cd dune-mmesh && git checkout bugfix/utility

RUN /dune/dune-common/bin/dunecontrol --opts=dune-mmesh/cmake/config.opts all

RUN . /dune/dune-common/build-cmake/dune-env/bin/activate && \
    pip install -e /dune/mmdgpy

