name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        mpi: ['openmpi']

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libopenmpi-dev openmpi-bin libsuitesparse-dev gmsh libboost-all-dev libmpfr-dev
      shell: bash
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup venv
      run: |
        python3 -m venv dune-env
        source dune-env/bin/activate
        python -m pip install --upgrade pip
        python -m pip install matplotlib scipy gmsh nbconvert
        python -m pip install flake8 pytest
      shell: bash
    - name: Install mmdgpy
      run: |
        source dune-env/bin/activate
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Lint with flake8
      run: |
        source dune-env/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude dune-env
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude dune-env
    - name: Test with pytest
      run: |
        source dune-env/bin/activate
        python -m pytest test/test_dg.py
        python -m pytest test/test_mmdg.py
